# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x12\x0esemantic_cache\",\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"#\n\x11\x45mbeddingResponse\x12\x0e\n\x06vector\x18\x01 \x03(\x02\"/\n\rQueryResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x0e\n\x06\x63\x61\x63hed\x18\x02 \x01(\x08\x32`\n\x0e\x45ncoderService\x12N\n\x0cGetEmbedding\x12\x1b.semantic_cache.TextRequest\x1a!.semantic_cache.EmbeddingResponse2\\\n\x0e\x43oreAppService\x12J\n\x0cProcessQuery\x12\x1b.semantic_cache.TextRequest\x1a\x1d.semantic_cache.QueryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTREQUEST']._serialized_start=29
  _globals['_TEXTREQUEST']._serialized_end=73
  _globals['_EMBEDDINGRESPONSE']._serialized_start=75
  _globals['_EMBEDDINGRESPONSE']._serialized_end=110
  _globals['_QUERYRESPONSE']._serialized_start=112
  _globals['_QUERYRESPONSE']._serialized_end=159
  _globals['_ENCODERSERVICE']._serialized_start=161
  _globals['_ENCODERSERVICE']._serialized_end=257
  _globals['_COREAPPSERVICE']._serialized_start=259
  _globals['_COREAPPSERVICE']._serialized_end=351
# @@protoc_insertion_point(module_scope)
